name: pr

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: â¬‡ Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'

      - name: ğŸ”¨ Build
        run: go build -v ./...
  
  lint:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - name: â¬‡ Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'

      - name: ğŸ” Lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          working-directory: /
          args: --timeout=30m

  test:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4

      - name: â¬‡ Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'

      - name: ğŸ”¨ Build
        run: go build -v ./...

      - name: ğŸ§ª Test
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic